swagger: "2.0"

info:
  title: Hello World
  version: "1.0"
basePath: /swagger

paths:
  /greeting/{name}:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: hello.post_greeting
      responses:
        '200':
          description: greeting response
          schema:
            type: string
            example: "hello dave!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
